version: '3.8'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: ./.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    volumes:
      - static_volume:/app/build/static

  gateway:
    build: ./nginx/
    volumes:
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
