version: '3.8'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: pavellagerev/kittygram_backend
    env_file: ./.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  frontend:
    image: pavellagerev/kittygram_frontend
    volumes:
      - static_volume:/app/build/static

  gateway:
    image: pavellagerev/kittygram_gateway
    volumes:
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    ports:
      - "9000:80"
