name: Kittygram Full CI/CD Workflow

on: [push]

jobs:
  tests_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_DB: kittygram
          POSTGRES_USER: kittygram_user
          POSTGRES_PASSWORD: kittygram_password
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
    - name: Run Django tests
      env:
        DB_NAME: kittygram
        DB_USER: kittygram_user
        DB_PASSWORD: kittygram_password
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        SECRET_KEY: 'ci-secret-key'
      run: |
        cd backend/
        python manage.py test

  tests_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        cd frontend/
        npm ci
    - name: Test frontend
      run: |
        cd frontend/
        npm run test

  build_and_push_to_docker_hub:
    name: Push Docker images to DockerHub
    runs-on: ubuntu-latest
    needs: [tests_backend, tests_frontend]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push backend to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: ./backend/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_backend:latest
    - name: Push frontend to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend:latest
    - name: Push gateway to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: ./nginx/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          if [ -d "kittygram_final" ]; then
            cd kittygram_final
            git pull
          else
            git clone https://github.com/Chashkapluy1/kittygram_final.git
            cd kittygram_final
          fi
          echo "${{ secrets.DOT_ENV }}" > .env
          sudo docker compose -f docker-compose.production.yml pull
          sudo docker compose -f docker-compose.production.yml up -d --force-recreate
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
          sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic --no-input
          sudo docker image prune -f

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ✅ Деплой проекта Kittygram успешно выполнен!
          
           **Инициатор:** ${{ github.actor }}
           **Коммит:** "${{ github.event.commits[0].message }}"
          
           **Посмотреть коммит:** https://github.com/${{ github.repository }}/commit/${{ github.sha }}
